name: Pull Request Test

on:
  workflow_dispatch:
  pull_request:
    types: [edited, synchronize, opened, reopened]

jobs:
  pull-request-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            //console.log(context.payload)
            //console.log(context.payload.pull_request.body);
            console.log(github.issues)
            let isLinked=false;
            let isInvalidIssue=false;
            let referencesOnlyOneIssue = false;
            let body = context.payload.pull_request.body;

            const re = /(Closes|Fixes) #[0-9]+ /g;
            const matches = body.match(re);
            console.log(matches);
            
            if(matches){
              
            }
            
            //(Closes|Fixes) #[0-9]+ 
