name: Pull Request Test

on:
  workflow_dispatch:
  pull_request:
    types: [edited, synchronize, opened, reopened]

jobs:
  pull-request-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            //console.log(context.payload)
            let isLinked=false;
            let invalidIssue=false;
            let body = context.payload.pull_request.body;
            const re = /(Closes|Fixes) #[0-9]+ /g;
            const matches = body.match(re);
            console.log(matches);
            //(Closes|Fixes) #[0-9]+ 
