name: Pull Request Test

on:
  workflow_dispatch:
  pull_request:
    types: [edited, synchronize, opened, reopened]

jobs:
  pull-request-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const ISSUE_LINK_REGEX_TO_MATCH = /(Closes|Fixes) #[0-9]+ /g;
            
            console.log(context.repo);
            
            // check that PR description contains required issue link
            if(!context.payload.pull_request){
              core.setFailed('There was no Pull Request data available to confirm issue link');
              return;
            }
            
            let prBody = context.payload.pull_request.body;
            console.log(prBody);
            
          
            //const response = await fetch('https://official-joke-api.appspot.com/random_joke');
            //const data = await response.json();
            //console.log(data);
            
            //core.setFailed("No Linked Issue Found!");
          
            //console.log(context.payload)
            //console.log(context.payload.pull_request.body);
            //console.log(github.issues)
            
            //let isLinked=false;
            //let isInvalidIssue=false;
            //let referencesOnlyOneIssue = false;
            //let body = context.payload.pull_request.body;

            //let issues = github.rest.issues.get({
            //  repo: context.repo.repo,
            //});
            //console.log(issues);

            //const re = /(Closes|Fixes) #[0-9]+ /g;
            //const matches = body.match(re);
            //console.log(matches);
            
            //if(matches){
              
            //}
            
            //(Closes|Fixes) #[0-9]+ 
