name: Pull Request Test

on:
  workflow_dispatch:
  pull_request:
    types: [edited, synchronize, opened, reopened]

jobs:
  pull-request-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const { payload } = context;
            console.log(payload);
            const ORG = payload.organization.login;
            const REPO = payload.repository.name;
            const REPO_BASE_API_URL = `https://api.github.com/repos/${ORG}/${REPO}`;
            const ISSUE_LINK_REGEX = /(Closes|Fixes) #[0-9]+ /g;
            
            console.log('Checking for existance of Pull Request data');
