name: Pull Request Test

on:
  workflow_dispatch:
  pull_request:
    types: [edited, synchronize, opened, reopened]

jobs:
  pull-request-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const { payload } = context;
            
            console.log(payload);
