name: Pull Request Test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]

jobs:
  pull-request-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context.payload)
            //(Closes|Fixes) #[0-9]+ 
